name: Build Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: Fetch Source code
       uses: actions/checkout@v4

     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'

     - name: Maven test
       run: mvn test

     - name: Checkstyle
       run: mvn checkstyle:checkstyle


