name: Build Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: Fetch Source code
       run: echo "Workflow test runs"
       uses: actions/checkout@v4

     - name: Maven test
       run: mvn test

     - name: Checkstyle
       run: mvn checkstyle:checkstyle


